import { z } from "zod";
export const CONTENT = {
  brand: {
    name: "Gần nhau",
    short: "Gần nhau",
    tagline: "Một chút mỗi ngày, một mình cũng được.",
    description:
      "Không gian riêng của hai người: lời nhắn, kỷ niệm và những điều mong ước.",
  },
  common: {
    save: "Lưu lại",
    cancel: "Hủy",
    delete: "Xóa",
    edit: "Sửa",
    loading: "Đang tải…",
    empty: "Chưa có gì ở đây. Mình bắt đầu nhé?",
    success: "Đã lưu lại.",
    retry: "Thử lại",
    back: "Quay lại",
    more: "Xem thêm",
    close: "Đóng",
    private: "Chỉ mình tôi",
    shared: "Cả hai",
    partner: "Gửi người ấy",
    confirmDelete: "Xóa nội dung này? Thao tác này không thể hoàn tác.",
    unsaved: "Bạn còn nội dung chưa lưu.",
    all: "Tất cả",
    mine: "Của tôi",
    theirs: "Của người ấy",
    search: "Tìm trong những lời nhắn…",
    days: "ngày",
    yes: "Đồng ý",
    count: "{{count}}",
    date: "Ngày",
    name: "Tên",
    title: "Tiêu đề",
    content: "Nội dung",
    visibility: "Ai có thể xem?",
    author: "Người viết",
    filters: "Bộ lọc",
  },
  nav: {
    home: "Hôm nay",
    daily: "Mỗi ngày",
    notes: "Lời nhắn",
    prayer: "Dòng ước nguyện",
    memories: "Kỷ niệm",
    activities: "Chán rồi?",
    settings: "Hai đứa",
    admin: "Hệ thống",
    privacy: "Riêng tư",
  },
  auth: {
    title: "Một nơi dành cho hai đứa",
    intro: "Để khoảng cách có thêm những điều nhỏ bé đáng chờ.",
    email: "Email",
    password: "Mật khẩu",
    name: "Tên bạn",
    signIn: "Đăng nhập",
    signUp: "Tạo tài khoản",
    switchSignUp: "Chưa có tài khoản? Đăng ký",
    switchSignIn: "Đã có tài khoản? Đăng nhập",
    signOut: "Đăng xuất",
    confirm: "Kiểm tra email để xác nhận tài khoản rồi đăng nhập.",
    forgot: "Quên mật khẩu",
    reset: "Đổi mật khẩu",
    sent: "Đã gửi email khôi phục.",
    newPassword: "Mật khẩu mới",
    setup: "Cần cấu hình kết nối trước khi bắt đầu",
    setupBody:
      "Điền biến môi trường và chạy migration theo README để đăng nhập. Những khóa này do người quản lý ứng dụng thiết lập.",
  },
  couples: {
    timezoneLocked:
      "Múi giờ được cố định từ ngày đầu tiên để tránh ghi nhận hoạt động hai lần trong một ngày.",
    title: "Hẹn người ấy vào đây",
    description:
      "Tạo một không gian riêng, rồi gửi mã cho người ấy. Hoặc nhập mã bạn đã nhận.",
    create: "Tạo không gian",
    join: "Nhập mã để ghép đôi",
    code: "Mã mời",
    invite: "Mã mời của hai đứa",
    expires: "Mã hết hạn sau 7 ngày.",
    rotate: "Tạo mã mới",
    leave: "Rời không gian chung",
    confirmLeave:
      "Rời không gian này? Bạn sẽ mất quyền xem dữ liệu chung. Dữ liệu được giữ lại cho người còn ở trong không gian.",
    waiting: "Không gian đang chờ người ấy.",
    timezone: "Múi giờ của hai đứa",
    timezones: [
      "Asia/Ho_Chi_Minh",
      "Asia/Bangkok",
      "Asia/Tokyo",
      "Asia/Seoul",
      "Europe/London",
      "Europe/Paris",
      "America/New_York",
      "America/Los_Angeles",
      "Australia/Sydney",
      "UTC",
    ],
    start: "Ngày bắt đầu",
    profile: "Tên gọi của bạn",
    connected: "Đã ghép đôi",
  },
  home: {
    eyebrow: "NHỮNG ĐIỀU NHỎ CỦA HAI ĐỨA",
    greeting: "Hôm nay mình thế nào?",
    daily: "Một câu hỏi, hai câu trả lời",
    dailyDesc: "Chỉ cần vài phút. Câu trả lời được mở khi cả hai cùng viết.",
    write: "Viết một chút",
    prayer: "Thả một điều mong ước",
    prayerDesc: "Gấp những điều khó nói vào một chiếc thuyền.",
    activity: "Làm gì cùng nhau?",
    memory: "{{count}} kỷ niệm đã giữ",
    streak: "{{count}} ngày kết nối",
    longest: "Dài nhất: {{count}} ngày",
    pending: "Bạn có thể viết trước, người ấy đến sau.",
    completed: "Hôm nay hai đứa đã viết xong.",
    repair: "Nối lại chuỗi",
    repairHint: "Dùng một lượt để nối qua một ngày bỏ lỡ. Mỗi tháng có 2 lượt.",
    partner: "Người ấy",
    you: "Bạn",
    week: "Một góc cuối tuần",
    weekDesc: "Không cần giải quyết tất cả ngay hôm nay.",
    special: "Ngày đáng mong",
    countdown: "Còn {{count}} ngày",
    noPressure: "Chuỗi là một kỷ niệm, không phải bài kiểm tra tình yêu.",
  },
  streak: {
    completed: "Đã kết nối",
    missed: "Ngày nghỉ",
    repaired: "Đã nối lại",
    protected: "Được bảo vệ",
  },
  daily: {
    title: "Vài phút cho hai đứa",
    answer: "Điều bạn muốn chia sẻ…",
    submit: "Gửi câu trả lời",
    wait: "Đã giữ câu trả lời của bạn. Mình chờ người ấy một chút nhé.",
    reveal: "Hai câu trả lời hôm nay",
    history: "Những ngày đã viết",
    reply: "Một lời đáp ngắn…",
    react: "Gửi một trái tim",
    replied: "Đã gửi lời đáp",
    needPair: "Ghép đủ hai người để hoàn thành daily.",
  },
  notes: {
    leaveDraft:
      "Lời nhắn chưa được lưu lên ứng dụng. Rời trang và giữ bản nháp trên thiết bị này?",
    draftStorageError:
      "Không lưu được bản nháp trên thiết bị này. Hãy lưu lời nhắn trước khi rời trang.",
    searchScope:
      "Tìm trong các lời nhắn đã tải. Chọn Xem thêm để tìm cả những lời nhắn cũ hơn.",
    title: "Những lời để dành",
    subtitle: "Lời nhắn nhỏ, danh sách chung, hay điều chỉ mình biết.",
    new: "Viết lời nhắn",
    titlePlaceholder: "Đặt một cái tên…",
    bodyPlaceholder: "Hôm nay mình muốn nói…",
    type: "Loại lời nhắn",
    text: "Văn bản",
    checklist: "Danh sách",
    checklistHint: "Mỗi dòng là một mục. Chạm vào mục để đánh dấu.",
    pin: "Ghim",
    unpin: "Bỏ ghim",
    pinned: "Đã ghim",
    draft: "Bản nháp được giữ trên thiết bị nếu gửi chưa thành công.",
  },
  prayer: {
    title: "Dòng ước nguyện",
    subtitle: "Những điều dịu dàng cứ để dòng nước mang đi.",
    write: "Viết một điều ước",
    placeholder: "Cầu mong mình và người ấy luôn hạnh phúc…",
    release: "Thả thuyền",
    released: "Thuyền đã lên đường.",
    river: "Những chiếc thuyền của hai đứa",
    open: "Mở lá thư",
    archive: "Cất thuyền",
    draft: "Lưu bản nháp",
    drafts: "Những lá thư đang viết",
    resurface: "Để thuyền trở lại sau 30 ngày",
    prompt: "Một gợi ý nhỏ",
    count: "{{count}} / {{max}}",
    confirm: "Thả chiếc thuyền mang điều ước này?",
    returned: "Một điều ước cũ đã trở lại",
  },
  memories: {
    title: "Những ngày đã có nhau",
    subtitle: "Một dòng thời gian, không cần hoàn hảo.",
    new: "Giữ một khoảnh khắc",
    body: "Điều mình muốn nhớ…",
    photo: "Thêm ảnh (JPEG, PNG, WebP; tối đa 5 MB)",
    onThisDay: "Vào ngày này",
    types: {
      daily: "Mỗi ngày",
      prayer: "Ước nguyện",
      note: "Lời nhắn",
      activity: "Hoạt động",
      moment: "Khoảnh khắc",
      weekly: "Cuối tuần",
      special: "Ngày đặc biệt",
    },
  },
  moods: {
    title: "Cho người ấy biết bạn thế nào",
    happy: "Vui",
    tired: "Mệt",
    sad: "Buồn",
    stressed: "Áp lực",
    calm: "Bình yên",
    busy: "Đang bận",
    hug: "Ôm một cái",
    love: "Thương bạn",
    rest: "Nghỉ một chút nhé",
    more: "Mình nghe đây",
  },
  activities: {
    title: "Chán rồi? Mình làm gì nhé",
    subtitle: "Không nhất thiết phải gọi điện. Một điều nhỏ cũng đủ.",
    time: "Có bao nhiêu phút?",
    minutes: "{{count}} phút",
    energy: "Năng lượng hôm nay",
    low: "Ít thôi",
    normal: "Vừa đủ",
    high: "Rất nhiều",
    preference: "Muốn làm gì?",
    chat: "Trò chuyện",
    play: "Chơi",
    watch: "Xem",
    romantic: "Lãng mạn",
    future: "Lên kế hoạch",
    random: "Bất kỳ",
    choose: "Gợi ý cho hai đứa",
    reroll: "Đổi gợi ý",
    complete: "Đã làm cùng nhau",
    like: "Thích",
    dislike: "Chưa hợp hôm nay",
    none: "Chưa có gợi ý phù hợp. Thử thêm thời gian hoặc chọn bất kỳ.",
  },
  settings: {
    title: "Không gian của hai đứa",
    notifications: "Nhắc nhẹ mỗi ngày",
    enablePush: "Bật thông báo",
    disablePush: "Tắt thông báo",
    pushDenied: "Trình duyệt đã chặn thông báo. Hãy cho phép trong cài đặt.",
    pushUnsupported:
      "Trình duyệt này chưa hỗ trợ thông báo. Trên iPhone, thêm ứng dụng vào màn hình chính trước.",
    resurface: "Cho những điều ước cũ trở lại",
    saved: "Đã cập nhật.",
    install: "Cài ứng dụng",
    installHint:
      "Android: menu trình duyệt → Cài ứng dụng. iPhone: Chia sẻ → Thêm vào màn hình chính.",
    export: "Tải dữ liệu tôi có quyền xem",
    deleteAccount: "Xóa tài khoản",
    confirmAccount:
      "Xóa vĩnh viễn tài khoản và dữ liệu cá nhân của bạn? Dữ liệu chung do người ấy tạo vẫn được giữ.",
    special: "Thêm ngày đặc biệt",
    kind: "Loại ngày",
    kinds: {
      meetup: "Gặp nhau",
      birthday: "Sinh nhật",
      anniversary: "Kỷ niệm",
      custom: "Ngày riêng",
    },
    weekly: "Góc cuối tuần",
    weeklyQuestions: [
      "Khoảnh khắc mình thích nhất tuần này?",
      "Có điều gì khiến mình buồn?",
      "Mình muốn nhận thêm điều gì?",
      "Tuần sau mình muốn làm gì cùng nhau?",
    ],
  },
  notifications: {
    title: "Gần nhau",
    daily: "Người ấy đã viết câu trả lời hôm nay.",
    prayer: "Có một chiếc thuyền mới dành cho bạn.",
    reminder: "Nếu có vài phút, mình ghé góc nhỏ của hai đứa nhé.",
    resurface: "Một điều ước cũ của bạn vừa trôi trở lại.",
    special: "Hôm nay là một ngày đặc biệt của hai đứa.",
    memory: "Một kỷ niệm của hai đứa đang chờ.",
  },
  errors: {
    databaseSetup:
      "Chưa tải được dữ liệu vì Supabase chưa nhận diện bảng của ứng dụng. Kiểm tra đúng project, chạy migration và seed theo README rồi tải lại trang.",
    generic:
      "Chưa thực hiện được. Bạn thử lại nhé; nội dung đang viết vẫn được giữ.",
    auth: "Không đăng nhập được. Kiểm tra email, mật khẩu và xác nhận email.",
    credentials:
      "Email hoặc mật khẩu không đúng. Nếu chưa có tài khoản, chọn Đăng ký; nếu đã đăng ký, kiểm tra lại hoặc chọn Quên mật khẩu.",
    emailNotConfirmed:
      "Email chưa được xác nhận. Mở email xác nhận đăng ký và bấm liên kết trước khi đăng nhập.",
    emailDisabled:
      "Đăng nhập bằng email đang tạm ngừng. Vui lòng liên hệ người quản lý ứng dụng.",
    signupDisabled:
      "Ứng dụng hiện chưa nhận đăng ký mới. Nếu đã có tài khoản, chọn Đăng nhập.",
    emailExists:
      "Email này đã được đăng ký. Chọn Đăng nhập hoặc Quên mật khẩu.",
    weakPassword:
      "Mật khẩu chưa đáp ứng yêu cầu bảo mật. Hãy dùng mật khẩu dài hơn và kết hợp chữ hoa, chữ thường, số và ký tự đặc biệt.",
    invalidEmail: "Địa chỉ email chưa hợp lệ. Kiểm tra lại email đã nhập.",
    emailDelivery:
      "Ứng dụng chưa gửi được email xác nhận hoặc khôi phục mật khẩu. Vui lòng thử lại sau; nếu vẫn gặp lỗi, liên hệ người quản lý ứng dụng.",
    emailRate:
      "Đã đạt giới hạn gửi email. Vui lòng chờ rồi thử lại; kiểm tra cả thư mục spam nếu đang chờ email.",
    samePassword: "Mật khẩu mới cần khác mật khẩu hiện tại.",
    authExpired:
      "Phiên đăng nhập hoặc liên kết xác nhận đã hết hạn. Đăng nhập lại hoặc yêu cầu liên kết mới.",
    authConnection:
      "Không kết nối được tới dịch vụ đăng nhập. Kiểm tra kết nối mạng rồi thử lại.",
    authUnavailable: "Dịch vụ đăng nhập đang gặp sự cố. Vui lòng thử lại sau.",
    invalid: "Kiểm tra lại nội dung đã nhập.",
    invite: "Mã không còn dùng được hoặc không gian đã đủ hai người.",
    offline:
      "Bạn đang ngoại tuyến. Kết nối lại để xem dữ liệu riêng và gửi nội dung.",
    forbidden: "Bạn không có quyền thực hiện thao tác này.",
    repair: "Chỉ nối được một ngày bỏ lỡ và cần còn lượt trong tháng.",
    notFound: "Không tìm thấy trang này.",
    rate: "Bạn thao tác hơi nhanh. Chờ một chút rồi thử lại.",
  },
  system: {
    daily_maintenance: "Bảo trì mỗi ngày",
    streak_update: "Cập nhật chuỗi",
    prayer_resurface: "Thuyền trở lại",
    push_reminders: "Nhắc nhẹ",
    success: "Hoàn thành",
    error: "Cần kiểm tra",
    running: "Đang chạy",
    idle: "Chưa chạy",
  },
  admin: {
    title: "Trạng thái hệ thống",
    healthy: "Kết nối dữ liệu hoạt động",
    jobs: "Các lần bảo trì",
    counts: "Số bản ghi",
    notAdmin: "Trang này dành cho người quản lý.",
    check: "Kiểm tra",
    labels: {
      profiles: "Người dùng",
      couples: "Không gian",
      daily_prompts: "Câu hỏi",
      activities: "Hoạt động",
      prayers: "Ước nguyện",
      memories: "Kỷ niệm",
      push_subscriptions: "Thiết bị nhận thông báo",
    },
  },
  privacy: {
    title: "Riêng tư của hai đứa",
    paragraphs: [
      "Nội dung được lưu trong Supabase của người quản lý ứng dụng. Chỉ thành viên trong cùng không gian được xem nội dung chung; nội dung riêng chỉ người viết được xem.",
      "Câu trả lời daily chỉ mở cho người ấy khi cả hai đã gửi. Khi rời không gian, quyền đọc dữ liệu của không gian đó bị thu hồi.",
      "Ứng dụng không chấm điểm tình yêu, không phân tích tâm lý và không dùng lời nhắn để huấn luyện AI. Bản nháp có thể lưu trên thiết bị; đăng xuất sẽ xóa bản nháp tại thiết bị đó.",
      "Bạn có thể xuất dữ liệu đang có quyền xem, xóa lời nhắn hoặc xóa tài khoản trong phần Hai đứa. Người quản lý nên công bố địa chỉ liên hệ và chính sách lưu trữ của mình trước khi đưa ứng dụng cho người khác.",
    ],
  },
} as const;
// Typed keys are checked by TypeScript; validate essential content at runtime too.
z.object({
  brand: z.object({ name: z.string().min(1) }),
  errors: z.object({ generic: z.string().min(1) }),
  notifications: z.object({
    title: z.string().min(1),
    reminder: z.string().min(1),
  }),
})
  .passthrough()
  .parse(CONTENT);
export function interpolate(
  template: string,
  values: Record<string, string | number>,
): string {
  return template.replace(/{{(\w+)}}/g, (_, key) => String(values[key] ?? ""));
}
