// Original artwork: doita-test/cuts. Shared names preserve existing icon roles.
import { PUBLIC_SPACE_ART } from "./public-space-art";
export const DOODLE_ICONS = {
  UserPlus: PUBLIC_SPACE_ART["user-plus"],
  Link: PUBLIC_SPACE_ART.link,
  Copy: PUBLIC_SPACE_ART.copy,
  House: "/themes/sunset/icons/house.webp",
  NotebookPen: "/themes/sunset/icons/notebook-pen.webp",
  Ship: "/themes/sunset/icons/ship.webp",
  Camera: "/themes/sunset/icons/camera.webp",
  Sparkles: "/themes/sunset/icons/sparkles.webp",
  Users: "/themes/sunset/icons/users.webp",
  Plus: "/themes/sunset/icons/plus.webp",
  Pin: "/themes/sunset/icons/pin.webp",
  Feather: "/themes/sunset/icons/feather.webp",
  Bell: "/themes/sunset/icons/bell.webp",
  Volume2: "/themes/sunset/icons/volume-on.webp",
  VolumeX: "/themes/sunset/icons/volume-off.webp",
  Menu: "/themes/sunset/icons/menu.webp",
  X: "/themes/sunset/icons/x.webp",
  Check: "/themes/sunset/icons/check.webp",
  ChevronDown: "/themes/sunset/icons/chevron-down.webp",
  ChevronUp: "/themes/sunset/icons/chevron-up.webp",
  LogOut: "/themes/sunset/icons/log-out.webp",
  CircleCheck: "/themes/sunset/icons/circle-check.webp",
  CircleAlert: "/themes/sunset/icons/circle-alert.webp",
  ShieldCheck: "/themes/sunset/icons/shield-check.webp",
  Trash2: "/themes/sunset/icons/trash.webp",
  Eye: "/themes/sunset/icons/eye.webp",
  EyeOff: "/themes/sunset/icons/eye-off.webp",
  Heart: "/themes/sunset/icons/heart.webp",
  Calendar: "/themes/sunset/icons/calendar.webp",
  Flame: "/themes/sunset/icons/flame.webp",
  Sun: "/themes/sunset/icons/sun.webp",
  Moon: "/themes/sunset/icons/moon.webp",
  CloudRain: "/themes/sunset/icons/cloud-rain.webp",
  Wind: "/themes/sunset/icons/wind.webp",
  Leaf: "/themes/sunset/icons/leaf.webp",
  Hourglass: "/themes/sunset/icons/hourglass.webp",
  ThumbsUp: "/themes/sunset/icons/thumbs-up.webp",
  ThumbsDown: "/themes/sunset/icons/thumbs-down.webp",
};
export type IconName = keyof typeof DOODLE_ICONS;
